version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: "@vue/runtime-core"
    versions:
    - 3.0.10
    - 3.0.5
    - 3.0.6
    - 3.0.7
    - 3.0.8
    - 3.0.9
  - dependency-name: "@nodegui/nodegui"
    versions:
    - 0.29.0
    - 0.30.0
    - 0.30.1
  - dependency-name: bl
    versions:
    - 4.0.4
